# Basic Site Settings
locale        : "en-US"
site_theme    : "default"
title         : "Andrea's Homepage"
title_separator: "-"
name          : &name "Andrea Della Vecchia"
description   : &description "ML & Quant Research — Option Pricing • Stochastic Control • Kernel Methods"

# USER SITE CONFIG
url           : "https://andreadvecchia.github.io"
baseurl       : ""   # MUST stay empty for user/organization sites
repository    : "andreadvecchia/andreadvecchia.github.io"

# --- HEADER NAV: show ONLY these pages ---
# Make sure you have these pages in _pages/publications.md and _pages/cv.md
header_pages:
  - publications.md
  - cv.md

# Sidebar author card (only the links you want)
author:
  avatar        : "fototessera.jpeg"   # put your headshot at /profile.png (or /images/profile.png)
  name          : "Andrea Della Vecchia"
  bio           : "Postdoc @ EPFL"
  location      : "Lausanne, Switzerland"
  employer      : "EPFL - Swiss Finance Institute"
  email         : "andrea.dvecchia@gmail.com"

  # Academic sites
  googlescholar : "https://scholar.google.com/citations?user=aaeUheEAAAAJ&hl=en&oi=ao"

  # Code repos
  github        : "andreadvecchia"

  # Social
  linkedin      : "andrea-della-vecchia-28761a1b5"

  # All other fields left blank so they won’t show

# Publications section labels
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# Site settings
breadcrumbs    : false
future         : true
read_more      : "disabled"
atom_feed:
  hide         : true

# Reading / build
include:
  - .htaccess
  - _pages
  - files
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README

markdown       : kramdown
highlighter    : rouge

# Collections (keep publications enabled)
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope: { path: "", type: pages }
    values: { layout: single, author_profile: true }
  - scope: { path: "", type: publications }
    values: { layout: single, author_profile: true }

# Plugins (safe for GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

